-- 코드를 입력하세요
SELECT PLACES.ID, PLACES.NAME, PLACES.HOST_ID
FROM PLACES JOIN (
    SELECT HOST_ID, COUNT(HOST_ID) AS CNT
    FROM PLACES
    GROUP BY HOST_ID
) AS PL
ON PLACES.HOST_ID = PL.HOST_ID
WHERE PL.CNT > 1